### ISSUE TITLE
Issue starting KTailCtl

### ISSUE THREAD

**Issue by Justinzobel** [flathub/org.fkoehler.KTailctl#39] opened 2024-08-29 06:58 UTC
flatpak --user run org.fkoehler.KTailctl
[2024-08-29T16:27:22][warning][qrc:Peers.qml:10] qrc:Peers.qml:10:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
[2024-08-29T16:27:22][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight"
[2024-08-29T16:27:22][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value"
[2024-08-29T16:27:22][warning][qrc:Statistics.qml:22] qrc:Statistics.qml:22: TypeError: Cannot read property 'totalUpSpeed' of undefined
[2024-08-29T16:27:22][warning][qrc:Statistics.qml:27] qrc:Statistics.qml:27: TypeError: Cannot read property 'totalDownSpeed' of undefined
[2024-08-29T16:27:22][critical][/run/build/ktailctl/src/wrapper/logging.cpp:10] failed to suggest exit node: no preferred DERP, try again later

**Comment by Justinzobel** [comment] 2024-08-29 07:04
Ah OK so this is an issue when tailscale has logged out. Just needs some checking and maybe instead of exiting immediately, show a dialog saying `tailscale currently logged out, please login and start ktailctl again.`

**Comment by f-koehler** [comment] 2024-09-04 16:09
I agree, that needs to be handled better. It has been a known issue since the beginning and I should work on fixing this soon as it is bad user experience. I will close this as the issue is tracked here: https://github.com/f-koehler/KTailctl/issues/5

**Closed by f-koehler** 2024-09-04 16:09 UTC
